import * as stylex from '@stylexjs/stylex';
import { colors, radius } from './tokens.stylex';

export const s = stylex.create({
  app: { minHeight: '100vh', backgroundColor: colors.paper },
  header: { position: 'sticky', top: 0, zIndex: 20, backgroundColor: colors.ink, borderBottomWidth: 1, borderBottomStyle: 'solid', borderBottomColor: '#26434e' },
  nav: { maxWidth: 1280, marginInline: 'auto', minHeight: 82, paddingInline: 24, display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 24, '@media (max-width: 820px)': { alignItems: 'flex-start', flexDirection: 'column', paddingBlock: 14 } },
  brand: { display: 'flex', alignItems: 'center', gap: 14, textDecoration: 'none' },
  logo: { width: 76, height: 60, objectFit: 'contain', borderRadius: radius.sm },
  brandTitle: { color: colors.gold, fontFamily: 'Georgia, serif', fontWeight: 800, fontSize: 24, letterSpacing: '0.08em' },
  brandSub: { color: colors.paperMuted, fontFamily: 'Georgia, serif', fontSize: 11, lineHeight: 1.2, maxWidth: 230 },
  links: { display: 'flex', flexWrap: 'wrap', gap: 18, alignItems: 'center' },
  navLink: { color: colors.paper, textDecoration: 'none', fontSize: 12, fontWeight: 800, letterSpacing: '0.07em', textTransform: 'uppercase', paddingBlock: 8, borderBottomWidth: 2, borderBottomStyle: 'solid', borderBottomColor: 'transparent', ':hover': { color: colors.green, borderBottomColor: colors.green } },
  main: { minHeight: '70vh' },
  footer: { backgroundColor: colors.ink, color: colors.paperMuted, paddingBlock: 38, paddingInline: 24 },
  footerInner: { maxWidth: 1180, marginInline: 'auto', display: 'flex', justifyContent: 'space-between', gap: 24, flexWrap: 'wrap' },
  footerStrong: { color: colors.gold, fontFamily: 'Georgia, serif', fontWeight: 700 },
  page: { maxWidth: 1180, marginInline: 'auto', paddingBlock: 56, paddingInline: 24 },
  darkPage: { backgroundColor: colors.ink, color: colors.paper },
  hero: { position: 'relative', minHeight: 610, display: 'grid', alignItems: 'end', overflow: 'hidden', backgroundColor: colors.ink },
  heroImage: { position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover', opacity: 0.6 },
  heroPattern: { position: 'absolute', inset: 0, opacity: 0.28, backgroundImage: 'repeating-linear-gradient(135deg, transparent 0 22px, rgba(149,160,34,.16) 22px 23px), radial-gradient(circle at 78% 26%, rgba(201,164,83,.22), transparent 26%)' },
  heroScrim: { position: 'absolute', inset: 0, backgroundImage: 'linear-gradient(180deg, rgba(7,25,35,.15) 10%, rgba(7,25,35,.42) 48%, rgba(7,25,35,.96) 100%)' },
  heroContent: { position: 'relative', zIndex: 2, width: '100%', maxWidth: 1180, marginInline: 'auto', paddingInline: 24, paddingBottom: 54 },
  eyebrow: { color: colors.green, fontSize: 12, fontWeight: 900, letterSpacing: '0.18em', textTransform: 'uppercase', marginBottom: 14 },
  display: { color: colors.paperStrong, fontFamily: 'Georgia, serif', fontSize: 70, lineHeight: 0.98, maxWidth: 760, textWrap: 'balance', '@media (max-width: 700px)': { fontSize: 46 } },
  displayAccent: { color: colors.green },
  intro: { marginTop: 18, maxWidth: 670, color: colors.paperMuted, fontSize: 18, lineHeight: 1.65 },
  statusGrid: { display: 'grid', gridTemplateColumns: 'repeat(4, minmax(0, 1fr))', backgroundColor: colors.paperStrong, borderBottomWidth: 1, borderBottomStyle: 'solid', borderBottomColor: colors.line, '@media (max-width: 760px)': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' } },
  status: { paddingBlock: 22, paddingInline: 18, textAlign: 'center', borderRightWidth: 1, borderRightStyle: 'solid', borderRightColor: colors.line },
  statusLabel: { color: colors.blue, fontSize: 10, fontWeight: 900, letterSpacing: '0.12em', textTransform: 'uppercase' },
  statusValue: { marginTop: 6, color: colors.ink, fontFamily: 'Georgia, serif', fontWeight: 800, fontSize: 24 },
  section: { paddingBlock: 64, paddingInline: 24 },
  sectionInner: { maxWidth: 1180, marginInline: 'auto' },
  sectionTitle: { color: colors.blue, fontFamily: 'Georgia, serif', fontSize: 38, lineHeight: 1.1, textAlign: 'center', marginBottom: 10 },
  sectionLead: { maxWidth: 720, marginInline: 'auto', color: '#5d625e', textAlign: 'center', lineHeight: 1.65, marginBottom: 34 },
  rule: { width: 90, height: 2, backgroundColor: colors.gold, marginInline: 'auto', marginBottom: 24 },
  cardGrid: { display: 'grid', gridTemplateColumns: 'repeat(4, minmax(0, 1fr))', gap: 14, '@media (max-width: 900px)': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' }, '@media (max-width: 560px)': { gridTemplateColumns: '1fr' } },
  card: { backgroundColor: colors.paperStrong, borderWidth: 1, borderStyle: 'solid', borderColor: colors.line, borderRadius: radius.md, padding: 22 },
  roundNumber: { color: colors.gold, fontFamily: 'Georgia, serif', fontSize: 30, fontWeight: 800 },
  roundDay: { color: colors.blue, fontWeight: 900, letterSpacing: '0.08em', textTransform: 'uppercase', marginTop: 8 },
  roundTitle: { fontFamily: 'Georgia, serif', fontWeight: 800, fontSize: 20, marginTop: 12, color: colors.ink },
  muted: { color: '#6e716c', lineHeight: 1.5, marginTop: 8 },
  darkSection: { backgroundColor: colors.ink, color: colors.paper },
  darkTitle: { color: colors.gold, fontFamily: 'Georgia, serif', fontSize: 46, textAlign: 'center' },
  darkLead: { color: colors.paperMuted, maxWidth: 650, textAlign: 'center', marginInline: 'auto', marginTop: 12, lineHeight: 1.6 },
  featureGrid: { display: 'grid', gridTemplateColumns: '1.15fr .85fr', gap: 42, alignItems: 'center', '@media (max-width: 820px)': { gridTemplateColumns: '1fr' } },
  featureImage: { width: '100%', minHeight: 330, maxHeight: 520, objectFit: 'cover', borderRadius: radius.md, borderWidth: 1, borderStyle: 'solid', borderColor: '#36525c' },
  featurePlaque: { minHeight: 340, borderRadius: radius.md, borderWidth: 1, borderStyle: 'solid', borderColor: '#536c76', backgroundImage: 'radial-gradient(circle at center, rgba(201,164,83,.16), transparent 46%), repeating-linear-gradient(45deg, rgba(149,160,34,.08) 0 1px, transparent 1px 18px)', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', textAlign: 'center', padding: 30, boxShadow: 'inset 0 0 0 8px #0b222d' },
  plaqueMark: { width: 92, height: 92, borderRadius: 999, display: 'grid', placeItems: 'center', marginBlock: 18, borderWidth: 2, borderStyle: 'solid', borderColor: colors.gold, color: colors.gold, fontFamily: 'Georgia, serif', fontWeight: 900, fontSize: 58 },
  plaqueTitle: { color: colors.gold, fontFamily: 'Georgia, serif', fontSize: 30, fontWeight: 900, letterSpacing: '0.06em', textAlign: 'center' },
  plaqueSmall: { color: colors.paperMuted, fontWeight: 900, fontSize: 10, letterSpacing: '0.14em', textTransform: 'uppercase', textAlign: 'center' },
  goldLabel: { color: colors.green, fontWeight: 900, letterSpacing: '0.13em', textTransform: 'uppercase', fontSize: 11 },
  bigName: { color: colors.gold, fontFamily: 'Georgia, serif', fontSize: 44, lineHeight: 1.05, marginTop: 10 },
  button: { display: 'inline-flex', alignItems: 'center', justifyContent: 'center', marginTop: 22, minHeight: 44, paddingInline: 20, borderRadius: radius.sm, borderWidth: 1, borderStyle: 'solid', borderColor: colors.green, backgroundColor: 'transparent', color: colors.paper, textDecoration: 'none', fontWeight: 900, fontSize: 12, letterSpacing: '0.07em', textTransform: 'uppercase', cursor: 'pointer', ':hover': { backgroundColor: colors.green, color: colors.ink } },
  lightButton: { color: colors.blue, borderColor: colors.blue, ':hover': { backgroundColor: colors.blue, color: colors.white } },
  tableWrap: { overflowX: 'auto', borderRadius: radius.md, borderWidth: 1, borderStyle: 'solid', borderColor: '#36525c' },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: 14 },
  th: { textAlign: 'left', color: colors.green, backgroundColor: '#0b222d', paddingBlock: 13, paddingInline: 14, fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.08em' },
  td: { paddingBlock: 12, paddingInline: 14, borderTopWidth: 1, borderTopStyle: 'solid', borderTopColor: '#29434e', color: colors.paper },
  playerGrid: { display: 'grid', gridTemplateColumns: 'repeat(3, minmax(0, 1fr))', gap: 18, '@media (max-width: 850px)': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' }, '@media (max-width: 560px)': { gridTemplateColumns: '1fr' } },
  playerCard: { backgroundColor: colors.paperStrong, borderRadius: radius.md, borderWidth: 1, borderStyle: 'solid', borderColor: colors.line, padding: 20 },
  playerName: { color: colors.blue, fontFamily: 'Georgia, serif', fontSize: 22, fontWeight: 800 },
  badge: { display: 'inline-block', marginTop: 8, paddingBlock: 4, paddingInline: 8, borderRadius: 999, backgroundColor: '#e4e7be', color: colors.ink, fontSize: 11, fontWeight: 900 },
  years: { display: 'flex', gap: 4, flexWrap: 'wrap', marginTop: 14 },
  yearDot: { minWidth: 26, textAlign: 'center', paddingBlock: 3, paddingInline: 5, backgroundColor: '#dce39d', color: colors.ink, fontSize: 9, fontWeight: 800, borderRadius: 3 },
  archiveGrid: { display: 'grid', gridTemplateColumns: 'repeat(4, minmax(0, 1fr))', gap: 18, '@media (max-width: 850px)': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' }, '@media (max-width: 520px)': { gridTemplateColumns: '1fr' } },
  archiveCard: { display: 'block', textDecoration: 'none', backgroundColor: colors.paperStrong, color: colors.ink, borderRadius: radius.md, overflow: 'hidden', borderWidth: 1, borderStyle: 'solid', borderColor: '#38505a', ':hover': { transform: 'translateY(-2px)' } },
  archiveImage: { width: '100%', aspectRatio: '4 / 3', objectFit: 'cover', backgroundColor: '#17333f' },
  archiveBody: { padding: 18 },
  archiveYear: { fontFamily: 'Georgia, serif', fontSize: 28, fontWeight: 800, color: colors.blue },
  storyGrid: { display: 'grid', gridTemplateColumns: '.9fr 1.1fr', gap: 44, alignItems: 'start', '@media (max-width: 820px)': { gridTemplateColumns: '1fr' } },
  storyCopy: { fontFamily: 'Georgia, serif', fontSize: 18, lineHeight: 1.75, color: '#27383e' },
  storyParagraph: { marginBottom: 18 },
  quote: { fontFamily: 'Georgia, serif', fontSize: 30, fontWeight: 800, color: colors.blue, borderLeftWidth: 4, borderLeftStyle: 'solid', borderLeftColor: colors.green, paddingLeft: 20, marginTop: 34 },
  form: { display: 'grid', gap: 14, maxWidth: 680 },
  label: { display: 'grid', gap: 6, color: colors.paper, fontWeight: 800, fontSize: 12, textTransform: 'uppercase', letterSpacing: '0.06em' },
  input: { width: '100%', minHeight: 44, borderRadius: radius.sm, borderWidth: 1, borderStyle: 'solid', borderColor: '#536c76', backgroundColor: '#0f2a35', color: colors.paper, paddingInline: 12 },
  notice: { borderLeftWidth: 4, borderLeftStyle: 'solid', borderLeftColor: colors.gold, backgroundColor: '#102b36', padding: 18, color: colors.paperMuted, lineHeight: 1.6, marginBottom: 24 },
  memorialName: { fontFamily: 'Georgia, serif', color: colors.gold, fontSize: 32 },
  memorialPlaque: { minHeight: 320, borderRadius: radius.md, borderWidth: 1, borderStyle: 'solid', borderColor: '#c4bd9c', backgroundColor: '#f1eddc', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 12, padding: 28, boxShadow: 'inset 0 0 0 8px #e1dbc1' },
  memorialPlaqueDark: { backgroundColor: '#102b36', borderColor: '#536c76', boxShadow: 'inset 0 0 0 8px #0b222d' },
  memorialInitials: { width: 112, height: 112, borderRadius: 999, display: 'grid', placeItems: 'center', borderWidth: 2, borderStyle: 'solid', borderColor: colors.gold, color: colors.gold, fontFamily: 'Georgia, serif', fontWeight: 900, fontSize: 42 },
});